version: "3"

volumes:
  nexus-data:

services:
  nginx:
    build:
      context: nginx/
    networks:
      default:
        aliases:
          - gitlab.localhost
          - nexus3.localhost
          - nexus3-direct.localhost
    ports:
      - "${GITLAB_HTTP:-80}:80"
      - "${GITLAB_HTTP:-443}:443"
    restart: unless-stopped
    depends_on:
      - gitlab
      - oauth2-proxy
  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    volumes:
      - 'D:\code\gitlab\config:/etc/gitlab'
      - 'D:\code\gitlab\logs:/var/log/gitlab'
      - 'D:\code\gitlab\data:/var/opt/gitlab'
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.localhost'

        nginx['listen_port'] = 80
        nginx['listen_https'] = false

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v5.1.0
    environment:
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
      OAUTH2_PROXY_PROVIDER: gitlab
      OAUTH2_PROXY_CLIENT_ID: 81c5dec7c2c614b3431d1b682fc62f5b1d12e79fe7cc94cd592413ac7d1a270f
      OAUTH2_PROXY_CLIENT_SECRET: c49f9b711d2523a31e82d7b5aa8bb5d7e6a4f42270ac38584cb4beeb212e16bb
      OAUTH2_PROXY_UPSTREAMS: http://oauth2-proxy-nexus3
      OAUTH2_PROXY_LOGIN_URL: https://gitlab.localhost/oauth/authorize
      OAUTH2_PROXY_REDEEM_URL: https://gitlab.localhost/oauth/token
      OAUTH2_PROXY_REDIRECT_URL: https://nexus3.localhost/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://gitlab.localhost
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_NAME: "${OAUTH2_PROXY_COOKIE_NAME:-_oauth2_proxy}"
      OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET:-b5a588cac11b869e729fcd688b38e6df}"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
    restart: unless-stopped
    depends_on:
      - gitlab
      - oauth2-proxy-nexus3

  oauth2-proxy-nexus3:
    build:
      context: ../
      args:
        GO_TAGS: authprovider_gitlab
    environment:
      O2PN3_LISTEN_ON: 0.0.0.0:80
      O2PN3_SSL_INSECURE_SKIP_VERIFY: "true"
      O2PN3_AP_URL: http://gitlab
      O2PN3_NEXUS3_URL: http://nexus3:8081
      O2PN3_NEXUS3_ADMIN_USER: admin
      O2PN3_NEXUS3_ADMIN_PASSWORD: .uPATGyX-65Afa7
    restart: unless-stopped
    depends_on:
      - nexus3

  nexus3:
    image: sonatype/nexus3:3.22.1
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

networks:
  default:
